### ISSUE TITLE
转账的成功后callbackurl为传出txID

### ISSUE THREAD

**Issue by Liuxiongning12** [TP-Lab/tp-wallet-sdk#3]
android发起转账成功后，sdk回调成功OnSucess能拿到txID,但是传入的cabackUrl回调后，txID为空，官方语言如下callbackUrl string //回调url，例如：https://abc.com?action=transfer&qrcID=123，则回调结果为：
       https://abc.com?action=transfer&qrcID=123&result=0&txID=xxx
       其中result（0为用户取消，1为成功,2为失败）txID为执行成功的transactionHash，    这个txID为空

**Comment by NullPointerDuke** [comment]
你是哪种方式调用，SDK拉起钱包转账还是扫码？

**Comment by Liuxiongning12** [comment]
你好，我用sdk拉起钱包转账




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 中午12:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TP-Lab/tp-wallet-sdk] 转账的成功后callbackurl为传出txID (Issue #3)





 
你是哪种方式调用，SDK拉起钱包转账还是扫码？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NullPointerDuke** [comment]
App内有收到回调的hash吗？callbackUrl是没收到回调还是hash参数为空？把你的callbackUrl贴一下

**Comment by Liuxiongning12** [comment]
app内由收到回调的hash，但是callbackurl有回调hash但是参数为空，我的callbackurl如下http://120.25.237.152:20020/OnTransfer?action=transfer， 回调后，服务器收到的参数如下OnTransfer, txID:, result: 1&nbsp;&nbsp; txID为空




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月20日(星期一) 中午12:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [TP-Lab/tp-wallet-sdk] 转账的成功后callbackurl为传出txID (Issue #3)





 
App内有收到回调的hash吗？callbackUrl是没收到回调还是hash参数为空？把你的callbackUrl贴一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NullPointerDuke** [comment]
更新Android App版本到1.4.1再试下，新版本修复了这个问题
