### ISSUE TITLE
deeplink使用浏览器调用login后callbackUrl的返回错误

### ISSUE THREAD

**Issue by AlienegraGeek** [TP-Lab/tp-wallet-sdk#4]
我设置的callbackUrl格式（能成功交互）：http://192.xxx.x.xx:7788/TpTest

deeplink使用浏览器的`<a href>` login之后，成功获取到了result 1，但是callbackUrl的result 2报错（并且tp的app提示 授权不通过）：

`{"result":2,"message":"未能读取数据，因为它的格式不正确。","data":{"result":2,"ref":"TokenPocket","action":"login","protocol":"TokenPocket","uuID":"11111111111111","actionId":"11111111111.0"}}`

请问callbackUrl中的result如何设置，需要返回什么参数，能否给一个示例？

**Comment by justXyS** [comment]
钱包这边会通过json/post发送相关信息给callbackUrl，接口端验证没问题后返回的信息里包含 {"code":0} 表示通过，其他code表示验证不通过
