### ISSUE TITLE
DeepLink方式拉起钱包操作的回调地址应该传成什么方式？

### ISSUE THREAD

**Issue by 1482334540com** [TP-Lab/tp-wallet-sdk#5]
DeepLink方式拉起钱包操作的回调地址应该传成什么方式？ 然后回调的地址以及参数是什么样的呢？ 没有更加详细的文档说明呢？

**Comment by Developmc** [comment]
看下这个文档
https://app.gitbook.com/o/-MMF2gGTT6Gq6xOmiUtT/s/RjeSa1rqnubm9jQ67F9z/mobile-wallet/deeplink
