### ISSUE TITLE
如何用web3j把web3.utils.soliditySha3实现出来

### ISSUE THREAD

**Issue by dappbird** [TP-Lab/tp-wallet-sdk#6]
给个例子

**Comment by dappbird** [comment]
web3.utils.soliditySha3({t: 'string', v: 'Hello!%'}, {t: 'int8', v:-23}, {t: 'address', v: '0x85F43D8a49eeB85d32Cf465507DD71d507100C1d'});
> "0xa13b31627c1ed7aaded5aecec71baf02fe123797fffd45e662eac8e06fbe4955"
http://cw.hubwiz.com/card/c/web3.js-1.0/1/8/8/
这个就是新加的 签名那个

**Comment by dappbird** [comment]
要对访问合约做身份验证

**Comment by dappbird** [comment]
在做sha3计算的时候， 我需要用web3j来实现 web3js里面的web3.utils.soliditySha3

**Comment by Developmc** [comment]
和 https://github.com/TP-Lab/Mobile-SDK/issues/31#issuecomment-1225072857 是同一问题
