### ISSUE TITLE
DeepLink方式拉起钱包授权登录 时报错 非法参数

### ISSUE THREAD

**Issue by mvpyb** [TP-Lab/tp-wallet-sdk#7]
const payload = {
        protocol : 'TokenPocket',
        version : '2.0',
        dappName : 'GroupSpace',
        dappIcon : `https://testing.alphagram.app/group-space-mobile/static/img/head-logo.30dff07c.svg`,
        blockchains : [
          {
            chainId : '108',
            network : 'ThunderCore Mainnet'
          }
        ],
        action : 'login',
        // actionId : '0xc89b68E48EA177c9dCb98eE4aB706689160157b4',
        actionId : new Date().valueOf().toString(),
        callbackUrl : href
      }
这是全连接 ：  url = `tpoutside://pull.activity?param=${encodeURI( JSON.stringify( payload ) )}`
然后打开该链接后提示非法参数

目前我主要有一下几个疑问 ：
1 param 中哪些参数是必填的
2 dapp是不是一定要在tp钱包内置应用市场上架过呢？（如果我是第一个第三方H5页面可不可以使用）
3 如果我当前是一个第三方H5页面，param 中的dappName icon actionId 这些值怎么填写

**Comment by Developmc** [comment]
问题一：network : 'ThunderCore Mainnet' 这个参数错了，应该是 network : 'ethereum' 。param参数请参考文档
https://app.gitbook.com/o/-MMF2gGTT6Gq6xOmiUtT/s/RjeSa1rqnubm9jQ67F9z/mobile-wallet/deeplink#shi-yong-fang-shi

问题二：不需要在钱包内上架

问题三： dappName和icon是开发者自定义的，填你们项目的名称和logo就行了；actionId是标识当前操作的，是自定义的一个字符串(如时间戳)

**Comment by mvpyb** [comment]
好的，多谢
